---
title: 'Research Report: Conclusions'
author: "Valentin"
date: "02/02/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Target question: 1. How do annual members and casual riders use Cyclistic bikes differently?**

**1. From the SQL analysis we got:**

Casual riders decreases from an average of **44.82%** from **March to October**, to an average of **24.25%** for the months of November, December, January and February. Meanwhile during **May, June, July and August** the quantity of each type of rider is pretty balanced.

Almost exclusively casual riders use docked bikes, though the average percentage per month is **4.9%** of the total riders, while for members the percentage is basically **0%**. However, **May, Jun, July and August**, corresponding to casual riders using classical bikes are a good potential target with an average of **26.76%** per month of the total of riders, while the respective percentage for members in this months is **33.71%**.

During months **May, Jun, July, August**, the use of the service by casual riders increases a lot and in particular from **16:00 to 24:00 hours**, the peak being from **16:00 to 20:00** hours with an average percentage of **16.8%** of casual riders vs a **17.1%** of members. So, this is another good target subset.

Casual riders use the service a lot on Saturdays and Sundays with a percentage of **9.35%** of the total riders for the whole year, while the percentage for member riders is **7.5%** for these days; but the rest of the week member riders use the service more. Also we note that for months **May, June, July and August** the use of casual riders increases for each day of the weak, from a percentage of **2.32%** in January from Monday to Friday, to an average percentage of **5.83%** for the indicated months.

Above 12 minutes, usual riders are the kind of riders using mostly the service, though with small percentage. In other words, member riders prefer to use the service for less ride duration, while usual riders prefer using the service for longer rides.

**2. From the R analysis we got:**

Annually with percentage above **2%** and for each type of rider, stations located at Clark street are by far the most used station for both type of riders with a percentage near to **7.6%** for each type. For casual riders there are specific streets used only by them, these are: **Ashland, DuSable, Lake, Streeter** with a total of **10.6%** of the total of casual members. 

With monthly percentage above **2.5%** and for each type of rider, Clark is still the most used one for both type of riders. We can also observe  that the streets **Broadway, Lake, Wells**, are used by casual members through out each month of the year.

### Final conclusion

The most profitable months for targeting casual riders are **May, June, July and August.**. The most profitable days during the whole year are **Saturdays and Sundays,** but casual riders tends to increase the use of the service through the whole week for the months **May, June, July and August.** Consider also that the most profitable hours are from **16:00 to 20:00** hours with rides duration preference for casual riders above 12 minutes. And finally we have that the preferred streets by casual riders are: **Clark, Broadway, Wells,Ashland, DuSable, Lake, Streeter**. 











